//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabSQL2Entities : DbContext
    {
        public LabSQL2Entities()
            : base("name=LabSQL2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Active_Companies_History> Active_Companies_History { get; set; }
        public virtual DbSet<ActiveCompanies> ActiveCompanies { get; set; }
        public virtual DbSet<Bankruptcy_History> Bankruptcy_History { get; set; }
        public virtual DbSet<Bransch> Bransch { get; set; }
        public virtual DbSet<Bransch_History> Bransch_History { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Customer_History> Customer_History { get; set; }
        public virtual DbSet<Economic_Association> Economic_Association { get; set; }
        public virtual DbSet<Economic_Association_History> Economic_Association_History { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Employee_History> Employee_History { get; set; }
        public virtual DbSet<Registered_Company> Registered_Company { get; set; }
        public virtual DbSet<Registered_Company_History> Registered_Company_History { get; set; }
    }
}
