//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bankruptcy
    {
        public int BranschId { get; set; }
        public int RegComp_Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Registered_Company Registered_Company { get; set; }
        public virtual Bransch Bransch { get; set; }
    }
}
