//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabSQL2Entities1 : DbContext
    {
        public LabSQL2Entities1()
            : base("name=LabSQL2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveCompanies> ActiveCompanies { get; set; }
        public virtual DbSet<Bankruptcy> Bankruptcy { get; set; }
        public virtual DbSet<Bransch> Bransch { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Economic_Association> Economic_Association { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Registered_Company> Registered_Company { get; set; }
    }
}
